### ISSUE TITLE
LDN processor should resolve the context URI (DASH-NRS) using a HEAD request to determine DSpace handle

### ISSUE THREAD

**Issue by wwelling** [harvard-lts/DSpace#30]
Currently, the LDN processer anticipates a DSpace handle to know which item it refers to. We need to support external resolver using DASH-NRS.

**Describe the solution you'd like**
Simple DASH-NRS URL HEAD request and get Location header of redirect as its handle.

**Comment by awoods** [comment]
Resolved by: https://github.com/harvard-lts/DSpace/commit/a80cbc38798629f233517ce22951fc20a59e9bee
