### ISSUE TITLE
Port NRS authority handle minting customizations

### ISSUE THREAD

**Issue by wwelling** [harvard-lts/DSpace#32]
https://github.com/harvard-lts/DASH/tree/main/dspace/modules/additions/src/main/java/edu/harvard/huit/lts/dash/nrs

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/DSpace/commit/2cf041d3ede44a25b8c71aa1b0b59f03035ac7d6

**Comment by awoods** [comment]
Follow-on clean-up: https://github.com/harvard-lts/DSpace/commit/59454f33271e457cbc9ee40fb748305197bc1fd4
