### ISSUE TITLE
External context id resolution should have URL validation from config

### ISSUE THREAD

**Issue by wwelling** [harvard-lts/DSpace#41]
When a notification is received, and the context id is not a DSpace URL we afford to use a HEAD request to resolve. This creates a vulnerability for notifications to be received in which attempt malicious HEAD requests.

Potential server-side request forgery due to [a user-provided value](https://lgtm.com/projects/g/DSpace/DSpace/snapshot/2f5eca7ae2253958947c8fb67398f3545e3f89d5/files/dspace-ldn/src/main/java/org/dspace/app/ldn/processor/LDNMetadataProcessor.java?sort=name&dir=ASC&mode=heatmap#x2c659545261898c3:1).

https://lgtm.com/rules/1513978414265/

To remedy this a configuration of a list of acceptable resolver base URLs should be added and used to validate the external context ids.

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/DSpace/commit/11ba270d2fee3c9d05e4d17d0a029a2456cecc64
