### ISSUE TITLE
Port LDN payload processors (multiple concrete specific processors)

### ISSUE THREAD

**Issue by wwelling** [harvard-lts/DSpace#6]
- To configurable LDN payload processor
  - Accept review processor configuration
  - Announce endorsement processor configuration
  - Announce review processor configuration
  - Reject review processor configuration

**Comment by awoods** [comment]
Resolved with: https://github.com/harvard-lts/DSpace/commit/baea50887c5489cff283d2ee7e19b9475f721bed
